---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
      day: monday
    commit-message:
      prefix: ci
    groups:
      deps:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
      day: monday
    commit-message:
      prefix: chore
    groups:
      deps:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      time: "07:00"
      day: monday
